controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    joint_state_controller:
      type: joint_state_controller/JointStateController

    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/jointTrajectoryController

forward_command_controller_position:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
